[cursor]
blink_interval = 500

[cursor.style]
blinking = "Off"

[font]
size = 12
builtin_box_drawing = true

[font.bold]
family = "Maple Mono NF CN"

[font.bold_italic]
family = "Maple Mono NF CN"

[font.italic]
family = "Maple Mono NF CN"

[font.normal]
family = "Maple Mono NF CN"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[window]
opacity = 0.80
decorations = "Full"
dynamic_title = true
resize_increments = true
