#! /bin/sh

# ..:: Start Task ::..

# startup scripts
sh ~/.config/scripts/startup.sh > /dev/null &

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkd/sxhkdrc &

# Polybar
sh ~/.config/polybar/polybar_startup.sh > /dev/null&

# picom
picom > /dev/null &

# Fcitx
fcitx5 > /dev/null &

# BackGround Image
feh --randomize --bg-scale ~/Pictures/WallPapers/* > /dev/null &

# Motrix
exec motrix &

# ScreenShot 
flameshot


# ..:: BSP Init ::..

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config border_width          1
bspc config window_gap            12
bspc config border_radius         80

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focus_follows_pointer true

#BSPWM coloring
#bspc config normal_border_color		"#4c566a"
#bspc config active_border_color		"#1e1e1e"
#bspc config focused_border_color	"#5e81ac"
#bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"
